"""
BEVFusion INT8 Deployment Configuration

Uses spconv INT8 for sparse encoder and pytorch_quantization for dense parts.

Two deployment modes:
A) With PTQ checkpoint (recommended):
   1. Run bevfusion_quantization.py ptq to produce a PTQ checkpoint
   2. Set checkpoint_path to the PTQ checkpoint
   3. Set quantization.ptq_checkpoint = True

B) Without PTQ checkpoint (runtime calibration only):
   1. Set checkpoint_path to original FP32 checkpoint
   2. Set quantization.ptq_checkpoint = False (default)
   3. Dense Q/DQ will be inserted but NOT calibrated (no _amax)

Usage:
    # For spconv_int8, use FX-traceable config (block_type='basicblock_fx'):
    #   config: bevfusion_*_120m_fx.py (same as base 120m, checkpoint compatible)

    # Step 1: Generate PTQ checkpoint
    python deployment/quantization/bevfusion_quantization.py ptq \
        --config projects/BEVFusion/configs/t4dataset/BEVFusion-L/bevfusion_lidar_voxel_second_secfpn_30e_4xb8_j6gen2_base_120m_fx.py \
        --checkpoint work_dirs/bevfusion/epoch_30.pth \
        --deploy-cfg deployment/projects/bevfusion/config/deploy_config_int8.py \
        --calibrate-samples 256 --batch-size 1 --calib-seed 0 \
        --output work_dirs/bevfusion/epoch_30_ptq2.pth

    # Step 2: Deploy with PTQ checkpoint (use same _fx config)
    python -m deployment.cli.main bevfusion \
        deployment/projects/bevfusion/config/deploy_config_int8.py \
        projects/BEVFusion/configs/t4dataset/BEVFusion-L/bevfusion_lidar_voxel_second_secfpn_30e_4xb8_j6gen2_base_120m_fx.py \
        --module main_body

    # Optional: split sparse/dense ONNX + engines (route 1) with same PTQ checkpoint
    #   → deployment/projects/bevfusion/config/deploy_config_split_int8.py

Docker (awml-bevfusion:full): set FX trace before spconv import and install quant tools, e.g.:
    export SPCONV_FX_TRACE_MODE=1
    pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com pytorch-quantization==2.1.3
    # (use --extra-index-url for NVIDIA PyPI; do not pass two --index-url)
"""

# ============================================================================
# Checkpoint Path
# ============================================================================
# For PTQ: use the PTQ checkpoint generated by bevfusion_quantization.py
# For FP32: use the original training checkpoint
checkpoint_path = "work_dirs/bevfusion/bevfusion_epoch_30_ptq.pth"

# ============================================================================
# Quantization Configuration
# ============================================================================
quantization = dict(
    enabled=True,
    # Set to True when using a PTQ checkpoint (contains calibrated _amax values)
    # Set to False when using original FP32 checkpoint (Q/DQ nodes will be uncalibrated)
    ptq_checkpoint=True,
    # Dense parts (backbone, neck, head): use pytorch_quantization (TensorQuantizer)
    fuse_bn=True,
    quant_backbone=True,
    quant_neck=True,
    quant_head=True,
    quant_add=False,
    # Sparse encoder (pts_middle_encoder): use spconv INT8 (cumm kernels)
    spconv_int8=True,
    # PTQ script + deploy loader both upgrade SparseBasicBlock→SparseBasicBlockFX before prepare_fx.
    # Set False only for legacy PTQ .pth files produced without that upgrade.
    spconv_ptq_basicblock_fx=True,
    # PTQ: effective spconv frames = max(--calibrate-samples, this); was 5 and starved FX observers.
    num_calibration_samples=40,
    # Sparse FX calibration: per-frame voxel cap (implicit_gemm ~O(N^2) on GPU). CLI: --spconv-calib-max-voxels.
    spconv_calib_max_voxels=4096,
    # Layers to skip quantization (prefix match)
    sensitive_layers=[],
)

# ============================================================================
# Device settings
# ============================================================================
devices = dict(
    cpu="cpu",
    cuda="cuda:0",
)

# ============================================================================
# Export Configuration
# ============================================================================
export = dict(
    mode="both",
    work_dir="work_dirs/bevfusion_int8_deployment",
    onnx_path=None,
)

_WORK_DIR = str(export["work_dir"]).rstrip("/")
_ONNX_DIR = f"{_WORK_DIR}/onnx"
_TENSORRT_DIR = f"{_WORK_DIR}/tensorrt"

# ============================================================================
# Component Configuration
# ============================================================================
components = dict(
    bevfusion_main_body=dict(
        onnx_file="bevfusion_lidar.onnx",
        engine_file="bevfusion_lidar.engine",
        io=dict(
            inputs=[
                dict(name="voxels", dtype="float32"),
                dict(name="coors", dtype="int32"),
                dict(name="num_points_per_voxel", dtype="int32"),
            ],
            outputs=[
                dict(name="bbox_pred", dtype="float32"),
                dict(name="score", dtype="float32"),
                dict(name="label_pred", dtype="int64"),
            ],
            dynamic_axes={
                "voxels": {0: "voxels_num"},
                "coors": {0: "voxels_num"},
                "num_points_per_voxel": {0: "voxels_num"},
            },
        ),
        tensorrt_profile=dict(
            voxels=dict(
                min_shape=[1, 10, 5],
                opt_shape=[64000, 10, 5],
                max_shape=[256000, 10, 5],
            ),
            coors=dict(
                min_shape=[1, 3],
                opt_shape=[64000, 3],
                max_shape=[256000, 3],
            ),
            num_points_per_voxel=dict(
                min_shape=[1],
                opt_shape=[64000],
                max_shape=[256000],
            ),
        ),
    ),
)

# ============================================================================
# Runtime I/O settings
# ============================================================================
runtime_io = dict(
    info_file="info/t4dataset_j6gen2_base_infos_test.pkl",
    sample_idx=0,
)

# ============================================================================
# ONNX Export Settings
# ============================================================================
onnx_config = dict(
    opset_version=17,
    do_constant_folding=True,
    export_params=True,
    keep_initializers_as_inputs=False,
    simplify=False,
    # Default unset: BEVFusion export uses CPU tracing (see BEVFUSION_ONNX_TRACE_DEVICE) because
    # pts_middle_encoder dense() can need tens of GB VRAM. Set trace_device="cuda:0" if you have enough GPU memory.
    # trace_device="cuda:0",
)

# ============================================================================
# TensorRT Build Settings
# ============================================================================
tensorrt_config = dict(
    precision_policy="fp16",
    max_workspace_size=1 << 32,
    plugin_libraries=["/opt/plugins/libautoware_tensorrt_plugins.so"],
)

# ============================================================================
# Evaluation Configuration
# Only PyTorch backend is enabled since spconv INT8 is not exportable.
# num_warmup_samples: runs to exclude from latency (reduces TensorRT cold-start variance).
# ============================================================================
evaluation = dict(
    enabled=True,
    num_samples=5,
    num_warmup_samples=2,
    verbose=True,
    backends=dict(
        pytorch=dict(
            enabled=True,
            device=devices["cuda"],
        ),
        onnx=dict(
            enabled=False,
            device=devices["cuda"],
            model_dir=_ONNX_DIR,
        ),
        tensorrt=dict(
            enabled=True,
            device=devices["cuda"],
            engine_dir=_TENSORRT_DIR,
        ),
    ),
)

# ============================================================================
# Verification Configuration
# ============================================================================
verification = dict(
    enabled=False,
    tolerance=1,
    num_verify_samples=1,
    devices=devices,
    scenarios=dict(
        both=[],
        onnx=[],
        trt=[],
        none=[],
    ),
)
